### ISSUE TITLE
Remove all references to Mandel

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/cdt#1]
Remove all references to `Mandel` or `mandel` from within the `antelope-3.0` branch of `cdt`. The submodule repos referenced from the `antelope-3.0` branch should not need any changes. There are mentions of mandel in `cdt-llvm` which are in reference to Mandelbrot and not the Mandel used in the context of EOSIO; these should not be touched.

Also, update the URLs referencing `eosnetworkfoundation` org repos to use the corresponding ones in the `AntelopeIO` organization.

After https://github.com/AntelopeIO/leap/issues/1 has been completed, ensure that you can still build CDT with integration tests (has dependency on Leap/EOSIO). In addition, ensure you can still build https://github.com/eosnetworkfoundation/mandel-contracts (with tests enabled) using the `antelope-3.1` branch of Leap and the `antelope-3.0` branch of CDT. It shouldn't be necessary to change `mandel-contracts` code to get it to work. 

It is acceptable to still have referenced to EOSIO in both Leap and CDT (even for package names and CMake files) even after this issue and https://github.com/AntelopeIO/leap/issues/1 are completed.

**Comment by CongPham05** [comment]
jhjhvvjhv
