### ISSUE TITLE
REQUEST: Versions for CDT and Contracts

### ISSUE THREAD

**Issue by bensig** [AntelopeIO/cdt#11]
Request: Could we please try to do versioning of CDT that matches the versions of antelope contracts? 

For example a CDT 2.0.0 should work on all antelope 2.x.x contracts and vice-versa.

Currently, switching and monitoring CDT versions is nightmarish.

**Comment by stephenpdeos** [comment]
Moving forward, we will have a clearer and more consistent process to communicate deprecations across releases with adequate adjustment timelines and communication channels. Grabbing the latest version of cdt now should alleviate this issue.

The EOS System Contracts will maintain their own separate versioning in the ENF org than versioning in Antelope.
