### ISSUE TITLE
Filename mismatch when using CONTRACT macro

### ISSUE THREAD

**Issue by DenisCarriere** [AntelopeIO/cdt#131]
## Issue

When using `CONTRACT`  macro, if the filename uses a `.` or different .cpp filename (ex: `eosio.faucet.cpp` ) it [causes an error `8000000000000000000`](https://github.com/AntelopeIO/cdt/blob/main/docs/08_troubleshooting/index.md#you-successfully-re-deployed-the-contract-code-but-when-you-broadcast-one-of-the-contracts-methods-to-the-blockchain-you-get-below-error-message) when deployed.

## Refactoring `eosio::contract` => `CONTRACT`

![telegram-cloud-photo-size-1-5010594579812035223-y](https://user-images.githubusercontent.com/550895/230632017-4d61d417-0f27-42e6-ad9e-426bdd8ae7e3.jpg)

![telegram-cloud-photo-size-1-5010594579812035224-y](https://user-images.githubusercontent.com/550895/230632037-a68c66b4-531f-4fc9-bdd4-a08d030905bc.jpg)

```bash
$ cdt-cpp eosio.faucet.cpp -I include
```

> `--contract=<string>` causes the same issue

[`eosio.time`](https://github.com/eosnetworkfoundation/eosio.time) repo

## Possible solutions
- Throw an error at compile time (contract name does not match filename)
  - Recommend alternative solution
  - throw error saying contract name mismatches filename
- By default use .cpp filename as contract name?
- Allow option for `--contract-name=<string>`

**Comment by ericpassmore** [comment]
closing duplication of #133
