### ISSUE TITLE
Using TABLE macro doesn't expose table in memory

### ISSUE THREAD

**Issue by DenisCarriere** [AntelopeIO/cdt#132]
## Issue

When refactoring code using TABLE macro, it doesn't seem to export the table name to memory, currently using Blanc++ to run these tests, however the CDT would possibly run into the same issues when https://github.com/AntelopeIO/cdt/issues/130.

### From using `eosio::table`
<img width="745" alt="image" src="https://user-images.githubusercontent.com/550895/230644345-f775f925-8f60-4f52-9c09-3847b1f5f8e2.png">

### To using TABLE macro

<img width="722" alt="image" src="https://user-images.githubusercontent.com/550895/230644420-334ea2ec-e7f3-4bfb-bc13-2d171a4115a8.png">

## ❌ Error

![telegram-cloud-photo-size-1-5010594579812035227-y](https://user-images.githubusercontent.com/550895/230644272-9a997269-13dd-41d8-835c-22eff7009129.jpg)

Test with contract: https://github.com/eosnetworkfoundation/eosio.saving

**Comment by stephenpdeos** [comment]
Because of the planned deprecation, no action. Discarding.
