### ISSUE TITLE
Support standard naming conventions for databases

### ISSUE THREAD

**Issue by nsjames** [AntelopeIO/cdt#135]
Right now we are using `emplace`, `modify`, and `erase` for the manipulation of rows in `multi_index` tables. 

Since we are expecting `multi_index` to be used in a similar way to a database within smart contracts, it would be easier for developers to get started with Antelope if our nomenclature mimicked that of other databases they are familiar with (like MySQL, Postgre, MongoDB, SQLite, etc) and had alias support for:
- Insert
- Update
- Delete

I think that the understandability and memorability of our language would improve for anyone who doesn't come from C++, Rust, or D. 

```cpp
users.insert(ram_payer, [&](auto& row){ ... });
users.update(user, ram_payer, [&](auto& row){ ... });
users.delete(user);
```

**Comment by mikelik** [comment]
@nsjames `delete` is a restricted keyword in C++ and cannot be used. May I use `remove` instead?

**Comment by mikelik** [comment]
Added insert, update and remove

**Comment by nsjames** [comment]
Heyy, I didn't even notice this. That's awesome 🔥
