### ISSUE TITLE
Review and update bin/cdt-* executable help information and man pages.

### ISSUE THREAD

**Issue by ScottBailey** [AntelopeIO/cdt#143]
`cdt-cpp --help` has a few issues. It seems worthwhile to review and correct this text. While we are at it, it seems useful to review all the cdt tools: `cdt-abidiff  cdt-cc  cdt-cpp  cdt-init  cdt-ld`.

Here are some cpp-cdt problem examples:
- `OVERVIEW: cdt-cpp (Eosio C++ -> WebAssembly compiler)`  Should Eosio be replaced by AntelopeIO?
- inconsistent termination: some help ends with a period while some does not
- `-O=<string>                     - Optimization level s, 0-3` - `string` could/should be `s` or something else? What about `-O3`? Is that valid? Evaluate this `--flag=<string>` for all similar options.
- is `--fnative` always x86_64?

**Comment by stephenpdeos** [comment]
More conversation within https://github.com/AntelopeIO/cdt/issues/121

**Comment by dimas1185** [comment]
most of points of a little to no value
