### ISSUE TITLE
Proposal of a new cdt-abidiff utility.

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/cdt#148]
Current cdt-abidiff looks very over engineered. In the PR #184  I propose a Python program which is 10 times shorter and IMHO has the same functionality, better error handling and works with the file paths more correctly.

**Comment by jolly-fellow** [comment]
The implementation PR #147  was merged by mistake because only one reviewer approval need for the merge.
 
In order to revert a PR I need to have administrator rights: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request

So IMHO it would be better if an administrator click the Revert button. It is easier than give me the rights.

**Comment by dimas1185** [comment]
`cdt-abidiff` is written in c++ and switching to python will change interface and also add python requirement. Also this is not actively developed utility so closing this one.
