### ISSUE TITLE
errors building EVM contract with 4.0

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/cdt#175]
I can't tell if this is something buggy in cdt or EVM contract. It's at least a regression for a contract that compiles fine in cdt 3.1

https://github.com/eosnetworkfoundation/eos-evm/actions/runs/4878774094/jobs/8704718768

**Comment by stephenpdeos** [comment]
Assumed to potentially be failing due to recent boost changes

**Comment by dimas1185** [comment]
this is better to fix on evm side:

here is the problem:
evm has
```c++
DataStream& operator<<(DataStream& ds, const std::basic_string<uint8_t>& bs)
```
defined as it wasn't defined in `cdt`

and `datastream` was recently enhanced with this one:
```c++
datastream<Stream>& operator << ( datastream<Stream>& ds, const std::basic_string<T>& s )
```

this causes `error: use of overloaded operator '<<' is ambiguous`.
Solution is to remove aforementioned code from `evm_contract.hpp`

**Comment by spoonincode** [comment]
Thanks for looking in to it; I went ahead and made eosnetworkfoundation/eos-evm#533 to track it over there
