### ISSUE TITLE
Support for EVM pieces

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#192]
For EOS-EVM, it has been highlighted that having the following data types and functions would be beneficial.

uint128, uint256, efficient to and from hex functions, others may be added in the next few days.

**Comment by mikelik** [comment]
Currently `uint128` is available in CDT as:
`typedef unsigned __int128 uint128_t;`

The task would be to write new uint128_t and benchmark it against existing __int128 and uint128 from https://github.com/chfast/intx/blob/master/include/intx/intx.hpp.

As for uint256 it is currently unavailable in CDT, so it has to be created and benchmarked.

Optionally benchmarked might be wide integers from boost multiprecision or https://github.com/abseil/abseil-cpp/blob/master/absl/numeric/int128.h

**Comment by mikelik** [comment]
Decision is to go with _BitInt(128) and _BitInt(256) which are supported by clang-16. BitInt is part of C23 standard.

**Comment by mikelik** [comment]
wide int to/from hex functions benchmark: https://github.com/mikelik/int128-benchmark/blob/main/hex.cpp

**Comment by mikelik** [comment]
https://github.com/mikelik/int128-benchmark 
Added benchmark hex conversion. Added new functions with improved performance by 30%

Following hex conversion functions has been chosen as fastest:
https://github.com/AntelopeIO/cdt/blob/mikelik/bitint/libraries/eosiolib/core/eosio/hex_conversion.hpp

**Comment by mikelik** [comment]
This is blocked by https://github.com/AntelopeIO/cdt/issues/185

**Comment by mikelik** [comment]
If someone picks this issue up they can start off from branch: https://github.com/AntelopeIO/cdt/tree/mikelik/bitint

**Comment by ericpassmore** [comment]
no longer a performance blocker, will re-open later
