### ISSUE TITLE
IF: CDT support for IF host function

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/cdt#210]
Depends on https://github.com/AntelopeIO/leap/issues/1511.

Add C++ wrapper for the new `set_finalizers` host function introduced with the IF protocol feature. Ensure this is added into a header file in a way that prevents a contract compiling with the new version of CDT but that does not actually use the new wrapper function from accidentally including `set_finalizers` as a dependency in the compiled WASM file. 

Should be done at same time as https://github.com/AntelopeIO/reference-contracts/issues/26 (Finalizer Action for Bios Contract)

**Comment by heifner** [comment]
The struct used for `set_finalizers` is:

```
struct finalizer_authority {
      std::string  description;
      uint64_t     fweight = 0;
      fc::crypto::blslib::bls_public_key  public_key;
};
struct finalizer_set {
   uint64_t fthreshold = 0;
   std::vector<finalizer_authority>finalizers;
};
```
