### ISSUE TITLE
Remove Or Fix Support for Apple and MacOS Compilation

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/cdt#212]
Investigate best approach for MacOS Builds. 
- Should we fix the existing build 
OR
- Remove specialized code for MacOS builds.

**Comment by spoonincode** [comment]
A thorough removal of macOS support may end up taking more work than trying to fix the existing macOS support. Best I could tell there is only one nagging issue -- `cdt-cpp -fnative` not adding the SDK's sysroot to the command line resulting in "Framework not found" errors. Granted, this may be tricky to solve, but unwinding all the various `#ifdef __APPLE__`s and such may not be straightforward either.

**Comment by spoonincode** [comment]
The fixes in the two linked PRs allow me to build and use cdt on latest macOS+Xcode with a M1 Mac Mini

**Comment by spoonincode** [comment]
4.0.x release branch is fully operational on latest macOS & xcode, closing this
