### ISSUE TITLE
Add possibility of specifying different target for integration tests

### ISSUE THREAD

**Issue by dimas1185** [AntelopeIO/cdt#216]
Currently integration tests work only with main branch and if you change the `target` it fails to find the package.
We need ability to have a custom `target` branch.
`target` variable is set here:
https://github.com/AntelopeIO/cdt/blob/d87749e732e88199db123abf024c4c2a3e2dab30/.github/workflows/build.yaml#L77C17-L77C17

example of PR fails due to this issue:
https://github.com/AntelopeIO/cdt/pull/203

**Comment by oschwaldp-oci** [comment]
@dimas1185 - For the current test case, could you specify which `cdt` branch and which `leap` branch you were looking to test with each other?

**Comment by oschwaldp-oci** [comment]
@dimas1185 - Currently the integration tests only run against `ubuntu20`, are you looking to expand them to run against `ubuntu22` (shouldn't be a problem as I believe `leap` is not putting up a `leap-dev` package for `ubuntu20` and `ubuntu22`) and also against `ubuntu-llvm`?  Currently `leap` doesn't have a `leap-dev` package being build/uploaded for a `ubuntu-llvm` platform.

**Comment by dimas1185** [comment]
branch we need from `leap` is `hotstuff_integration`. `cdt` one is not created yet, you can create one with the same name and try to point it to the corresponding `leap` branch.
we are not looking for expanding this beyond `ubuntu-20` for now
