### ISSUE TITLE
Stop using OLD CMake policy for CMP0002 

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/cdt#5]
In `CDTMacros.cmake` the `add_native_executable` macro uses `cmake_policy(SET CMP0002 OLD)`. Setting the OLD behavior for this policy has been deprecated in CMake which causes many warning when building CDT.

It is not clear to me why we are setting the OLD behavior for this policy, but we should figure out an alternative approach to avoid depending on deprecated behavior.

**Comment by larryk85** [comment]
This can't be removed. It is used to gloss over limitations with CMake and cross-compiling problems.  This will be a non-issue when we move to ANTLER as it will be a different system.
