### ISSUE TITLE
Project Management System (antler-proj) Validate project

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#67]
Verify that assumptions are matched for how the tool should function (dependency management, application construction, lib construction) as documentation is finalized

**Comment by BenjaminGormanPMP** [comment]
Issue moved to "Blocked" per stand-up (4/10/23):
• Postponed until ANTLER Proj in working state/clean-up outstanding bugs.

**Comment by stephenpdeos** [comment]
Because we have evaluated the project and created follow-on bugs, we can close this issue. All future validation will occur with the completion of outstanding bugs.
