### ISSUE TITLE
Switch to Google Protobuf for API serialization and deserialization.

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#71]
To aid in better support for smart contract APIs externally and to move to a more language agnostic approach of how we handle smart contract APIs.  
The system should move to using Google Protobufs to define actions.  This allows all languages we want to support in the future to have the same method of defining the API schemas, as they write a protobuf file and generate the code, as opposed to take C++ and generate JSON.  ABI generation has been error-prone since its inception because we are trying to shoe-horn a massive complex language into JSON.

As we move into the future with features like read-only actions and transactions, the proposed path is to only have 'actions' as the API, meaning that database accesses would be done via an action, and retrieving Ricardian contracts would be done via an action. This allows for smart contracts to extend the API and conventions they use without having to update a static format that really shouldn't be defining those things to begin with.

**Comment by stephenpdeos** [comment]
Labeling as more-info since it requires further breakdown to be acitonable

**Comment by ericpassmore** [comment]
too much work given our limited resources. Closing as won't fix
