### ISSUE TITLE
Testing Enviroment (antler-run) C and C++ wrappers for integration testing

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#85]
Given a testing environment like 'catch2' as the basis, we will create a set of abstractions to allow a test to create a node, set contracts, push actions, check the results of those actions.

For the first version of this framework it will be pretty small, and as we get input from developers we would prioritize that as needed.

**Comment by ericpassmore** [comment]
deprecating Antler closing issues as won't fix
