### ISSUE TITLE
missing support for `get_code_hash` host function

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/cdt#88]
cdt is missing support for the `get_code_hash` host function introduced with Antelope's `GET_CODE_HASH` protocol feature.

**Comment by nathanielhourt** [comment]
Well, while I wait for someone to notice #97 and #99 (wink wink nudge nudge), I decided to look around for something else I could help out with and chose this issue.

Check out PReq #109 and let me know if I missed anything. =)
