### ISSUE TITLE
Project Management System (antler-proj) documentation

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/cdt#95]

**Comment by jolly-fellow** [comment]
Description of the command line user interface, general architecture, algorithms and principles of work are added here: https://github.com/AntelopeIO/antler-proj/blob/main/docs/usecases.md

Writing of the User's Guide is in progress.

**Comment by stephenpdeos** [comment]
Closing this task for now as it is merged. Will draft a new ticket for next wave of documentation.
